### ISSUE TITLE
Potential for crash in scoring and weight correctness when node/edge bindings have empty ids

### ISSUE THREAD

**Issue by PhillipsOwen** [ranking-agent/aragorn-ranker#11]
both scoring and weight correctness are susceptible to crashing when result nodes have empty node/edge binding id values. a recent node normalization issue (see https://github.com/TranslatorSRI/NodeNormalization/issues/46) is known to cause this problem. there could be other vectors that could also create this issue/crash.

this behavor was found in the ranker_obj rank/score code (used by aragorn-ranker scoring) when determining non-set node ids. the array created with this missing id data had less that 2 members which caused a crash in the kirchhoff() method. 

this was also exhibited in the weight correctness code when creating an id based mapping array that links a result edge binding to a knowledge graph edge by id.

**Comment by cbizon** [comment]
Can you make a minimal TRAPI input that causes the error?  I think that any answer of this form:

(thing)-(set of things) 

should expose it

**Comment by cbizon** [comment]
Is this still an issue?

**Comment by PhillipsOwen** [comment]
i am fairly sure that you and i looked at this a month+ ago.

I will see if it still fails...

**Comment by PhillipsOwen** [comment]
this has been corrected and will be implemented in the next deploy
