### ISSUE TITLE
Handle set nodes.

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn-ranker#17]
Currently in /score we calculate the kirchoff index for the graph consisting of non-set nodes.  This is bad for 2 reasons

1. That's loosing a lot of information
2. Sometimes we don't have enough non-set nodes (need at least 2).  This can happen e.g. when you do a 1-hop and then AC does a property coalesce, ending up with (node)-(set of nodes) in the answers.

Currently, when we hit a situation in which there are insufficient numbers of non-set nodes, we return a score of 0, which is bogus.

What's the right approach for set nodes?

One option would be to create a node that acts like a single node, i.e. somehow accumulate the scores along edges coming into a set node so that it looks like a single thing.

Discovered while working on 
https://github.com/ranking-agent/aragorn/issues/11

**Comment by cbizon** [comment]
It seems as though the ranker in messenger did handle these nodes, so we need to revisit that code and see what happened.

From Patrick:
The resistance distance between non-set nodes takes into account the set nodes between them...
e.g. in similarity-type questions, we don't need or want to actually compute distances from set nodes to elsewhere, but useful information comes from computing distances across them
There's a special provision for leaf-set-nodes, where we pretend there is another node on the other side. 

All of the above should happen in /score.

**Comment by mmersmann** [comment]
Cleaned up how weight attributes are passed around. Need a good test to demonstrate fix.

**Comment by mmersmann** [comment]
Reminder: @cbizon to test.

**Comment by richakanwar13** [comment]
Per meeting on 9/24, can be closed.
