### ISSUE TITLE
TRAPI TIMELINE: 1.2 implementations

### ISSUE THREAD

**Issue by richakanwar13** [ranking-agent/aragorn-ranker#35]
**Due Date:** August 18
**Note:** 1.1 and 1.2 should run in parallel until we’re ready to shut off 1.1
[TRAPI 1.1 to 1.2 Change Log](https://github.com/NCATSTranslator/ReasonerAPI/pull/277/files).
[ReasonerAPI Reference Ticket](https://github.com/NCATSTranslator/ReasonerAPI/issues/271)

**Comment by mmersmann** [comment]
Complete, per Chris in Translator: RENCI Integration meeting.
