### ISSUE TITLE
Giant scores

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn-ranker#55]
https://arax.ncats.io/index.html?r=6ae8518e-7ce6-4732-9ac1-979186a29708

This query is returning some answers that have good scores, and some that are scored 10000000000000 (or so).

**Comment by kennethmorton** [comment]
The answer has been download and then reuploaded to QGraph for further inspection. 

https://robokop.renci.org:7080/answer/zGdj64dY

QGraph seems to handle larger messages like this much better when you need to see the full JSON details.

**Comment by kennethmorton** [comment]
I am still investigating but I believe we have a poorly formed matrix somewhere along the way such that numpy.trace returns something close to machine precision. We then invert this trace and these large values. 

It will take more detective work to figure out how this matrix is illformed for this particular question.

**Comment by cbizon** [comment]
I think that this issue is fixed, is that correct @raynCovar ?

**Comment by raynCovar** [comment]
Correct, should have closed it. Sorry about that.
